#version 450

layout (binding = 0) uniform UniformBufferObject {
    vec3 lightDirection;
    vec3 worldCamPos;
    mat4 model;
    int debugMode;
    vec3 diffuse;
} ubo;

layout(std430, binding = 1) buffer SSBOIn {
   float dataIn[ ];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() 
{
    uint index = gl_GlobalInvocationID.x;  

    dataIn[index] = ubo.lightDirection.x * ubo.debugMode * index;
}